### ISSUE TITLE
README refers to non-existent argument `opamFilename`

### ISSUE THREAD

**Issue by aherrmann** [timbertson/opam2nix-packages#22]
The README says that `buildOpamPackage` takes an argument called `opamFilename`.
In fact it is called `opamFile` (see [here](https://github.com/timbertson/opam2nix-packages/blob/c33e0053ad6e49808faac54516d558c7e5106f18/nix/default.nix#L43))

**Comment by timbertson** [comment]
Thanks, fixed in 3af26b4c3dab1d6355b66a848aa4e55c818dd428 :)
