### ISSUE TITLE
nativeBuildInputs in overrides

### ISSUE THREAD

**Issue by dysinger** [timbertson/opam2nix-packages#40]
I see pkgconfig in with buildInputs in overrides/default.nix

I was told when submitting packages to nixpkgs in a P/R that nativeBuildInputs should be used for these types of non-propagated setup tools. This helps with cross compiling (you don't have to recompile the whole tool-chain for pkgconfig when building something for arm on x86 because pkgconfig runs fine on the host.)

**Comment by dysinger** [comment]
https://github.com/NixOS/nixpkgs/issues/1915

**Comment by dysinger** [comment]
NM. I see commits. :) Thanks

**Comment by timbertson** [comment]
Yeah sorry, I mentioned you in the pr but forgot to link it to this issue.
