### ISSUE TITLE
Reproducible build environment?

### ISSUE THREAD

**Issue by apatil** [timbertson/opam2nix-packages#6]
If I build a Nix expression like https://github.com/apatil/crunchium/blob/opam2nix/default.nix, then several months later I clear out my Nix store & build it again, OPAM might find that newer package versions are available & I might get a new set of dependencies between the builds.

This behavior is a bug in some situations and a feature in others, so I'd ideally like to be able to opt in to a fully reproducible build environment. What would be a good way to do that?

**Comment by timbertson** [comment]
Actually, `opam2nix-packages` includes the state of the entire opam repo - we load the `repo/` folder into the solver, and that's all opam knows about. So just like `nixpkgs` you'll always have reproduce builds by default, the solver will never pick a different set of packages until you update `opam2nix-packages`.

If you're wondering when `repo/` gets regenerated, it's currently whenever I get around to it - I'm working on automating that in #3
